### [异步 Promise 期约](#)
> **介绍**：在早期的 JavaScript 中，只支持定义回调函数
来表明异步操作完成。串联多个异步操作是一个常见的问题，通常需要深度嵌套的回调函数（俗称“回
调地狱”）来解决。而现在JS直接支持异步操作。

-----
- [1. Promise期约](#1-promise期约)
- [2. 期约的实例方法](#2-期约的实例方法)
- [3. 期约连锁与期约合成](#3-期约连锁与期约合成)
- [4. 期约扩展](#4-期约扩展)
- [5. async和await](#5-async和await)

-----
### [1. Promise 期约](#)
ECMAScript 6 增加了对 Promises/A+规范的完善支持，即 Promise 类型。一经推出，Promise 就
大受欢迎，成为了主导性的异步编程机制。所有现代浏览器都支持 ES6 期约，很多其他浏览器 API（如
fetch()和 Battery Status API）也以期约为基础。

`Promise` 一旦定义完成就开始执行。编写一个经典的 Promise 程序 Promise 构造函数参数为一个执行函数，执行函数有两个参数。
* `resolve(any v)` 将期约状态设置为 fulfilled  成功 执行完成。
* `reject(any v)` 将期约状态设置为 rejected  失败 有错误。

```javascript
//新建一个抽奖异步进行
//抽奖成功 将Promise 设置为 fulfilled 并且传递抽到的随机数 否则设置为 rejected

let run = new Promise((resolve,reject) =>{
    let rum = Math.random() *10;
    if (rum > 2.0) {
        console.log("抽奖失败，未获得奖品，感谢惠顾！");
        reject(rum);////执行失败
    }else{
        console.log(`恭喜你，中奖了！获得现金：${ Math.ceil( (rum + 1) * 10)}元`);
        resolve(rum);//执行成功
    }
}).then(v => console.log("抽奖成功，抽到数值: " + v))  /* then 和 catch不可以反过来*/
  .catch(v => console.log("未获奖，损失资金:" + v)); /* 反过来了*/
```

#### [1.1 Promise 是一个状态机](#)
期约是一个有状态的对象，他只能处于以下三种状态之一：
1. 待定 pending。 待定是初始状态 期约只能从待定状态转换为 `对线状态` 或者 `拒绝状态`。然后保持。
2. 对线 fulfilled。 
3. 拒绝 rejected。

```css
                -----> fulfilled
                |
state pending ---
                |
                -----> rejected 
```
期约通过执行函数控制期约的状态。

#### [1.2 Promise 类](#)
通过构造一个 **Promise** 的对象创建一个实例，创建了一个异步操作。一旦创建完成操作就开始执行。

Promise的构造函数 需要传递一个参数。这个参数是一个函数 可以使用箭头函数 这个函数有两个参数。 `resolve` 和 `reject`,这两个参数都是函数
执行 resolve 可以将期约状态从 pending 转换为 `fulfilled` 执行 `reject` 可以将期约状态从 `pending` 转换为 `rejected`。 

这两个函数都可以传递一个参数 `resolve(value)`、`reject(reason)`;

一个Promise 只能有一此状态的改变，一旦改变就不可以再修改。

```javascript
let p = new Promise((resolve, reject) => { });

let p1 = new Promise((resolve, reject) => {
    resolve();
    reject();//没有效果
});

let p2 = new Promise((resolve, reject) => {
    resolve('成功了');
    reject(`失败了`);//没有效果
});
```
**Promise.resolve(value)**:返回一个状态为 fulfilled的期约 等于 `new Promise((resolve, reject)=> resolve(value))`。

**Promise.reject(reason)**:返回一个状态为 rejected的期约 等于 `new Promise((resolve, reject)=> reject(reason))`。
```javascript
let result = Promise.resolve(20).then( v=> { console.log(v)}); //20

let failed = Promise.reject('因为网络问题').catch(reason => {console.log(reason)});//因为网络问题
```

* Promise.then:接收两个参数，注册两个后续处理函数，第一个参数注册resolved时的处理函数，第二个参数注册rejected时的处理函数。我们通常用then来处理resolved，第二个参数可以不填
* Promise.catch：注册rejected时的处理函数，链式调用时，对catch以前的rejected都可以统一处理。
* Promise.finally：注册一个处理函数，无论resolved还是rejected都会执行。
* Promise.resolve：返回一个resolved状态的Promise对象，并可以传一个参数。
* Promise.reject：返回一个rejected状态的Promise对象，并可以传递一个参数。
* Promise.all：接收一个Promise对象的数组，当所有Promise对象都进入已决阶段时，执行并返回一个新的Promise对象 。若所有Promise的处理结果均为resolved，那么新返回的Promise对象状态为resolved，并传递一个拥有所有Promise对象resolved传值，并且按顺序排列的数组。若* Promise中有rejected状态，则新的Promise对象状态也为rejected，并传递第一个rejected的结果。
* Promise.race：接收一个Promise对象的数组，以第一个进入已决阶段的Promise结果为准。返回第一个已决Promise的结果作为新的Promise对象的结果。
* Promise.allSettled：接收一个Promise对象的数组，等待所有Promise已决，便进入resolved状态，传递所有Promise结果的数组。
* Promise.any：接收一个Promise对象的数组，当出现第一个resolve状态的Promise时，发生短路，并传递resolve值。若全部rejected则会抛出一个记录错误信息的数组。

#### [1.3 封装一个json 请求](#)
```javascript
const getJSON = function(url) {
    const promise = new Promise(function(resolve, reject){
        const handler = function() {
            if (this.readyState !== 4) {
                return;
            }
            if (this.status === 200) {
                resolve(this.response);
            } else {
                reject(new Error(this.statusText));
            }
        };
        const client = new XMLHttpRequest();
        client.open("GET", url);
        client.onreadystatechange = handler;
        client.responseType = "json";
        client.setRequestHeader("Accept", "application/json");
        client.send();
    });

    return promise;
};

getJSON("/posts.json").then(function(json) {
    console.log('Contents: ' + json);
}, function(error) {
    console.error('出错了', error);
});
```

#### [1.4 错误处理](#)
Promise的设计很大程度上会导致一种完全不同于JavaScript的设计模式。

1. 在Promise中抛出的错误，不会被外部 `try/catch` 捕获,**只能通过catch捕获**。
2. 不能在Promise中使用 `try/catch`,里面抛出的错误可以使用catch捕获处理。

```javascript
try {
  throw new Error('We got Error!');
} catch(e) {
  console.log(e); // Error: We got Error!
}

try {
  Promise.reject(new Error('We got Error!'));
} catch(e) {
  console.log(e); // Uncaught (in promise) Error: We got Error!
}
```
这种写法会报错无法执行了。
```javascript
let p1 = new Promise((resolve, reject) => {
    try{
        throw new Error('oh 出错了');
    }catch (e) {
        console.log(e);
    }
});
```
**正确写法**
```javascript
let p1 = new Promise((resolve, reject) => {
    reject(new Error('oh 出错了'));
}).catch(err => console.log(err.message));//oh 出错了
```
### [2. 期约的实例方法](#)
期约实例的方法是连接外部同步代码与内部异步代码之间的桥梁。这些方法可以访问异步操作返回的数据，处理
期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态时才会执行的代码。

#### [2.1 Thenable接口](#)
期约实例的方法是连接外部同步代码与内部异步代码之间的桥梁。这些方法可以访问异步操作返回的数据，处理期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态时才会执行的代码。

1. 实现Thenable接口:
2. 在 ECMAScript暴露的异步结构中，任何对象都有一个then() 方法。 这个方法就被认为实现了Thenable接口。

下面的例子展示了实现这一接口的最简单的类：
```javascript
class MyThenable{
    /* onResolved、onRejected 是两个函数 */
    then(onResolved, onRejected){
        /*...*/
    }
}
```
#### [2.1 Promise.prototype.then()](#)
Promise实例具有then方法，也就是说，then方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。
前面说过，then方法的第一个参数是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数。

then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。

```javascript
then(onResolved, onRejected);
```  

then返回一个Promise实例。then传入的两个参数是两个函数，这个两个函数只会执行一个。如果Promise状态是fulfilled.那么就执行onResolved函数。 如果状态是rejected那就就执行nRejected函数。`

```javascript
let pVal = new Promise((resolve, reject) => {
    let rum = Math.random() *10;
    if (rum > 5.0) {
        reject(rum);////执行失败
    }else{
        resolve(rum);//执行成功
    }
}).then(value => {
    console.log('i get a number small than (<) 5.0 ');
}, reason => {
    console.log('i get a number big than (>) 5.0 ');
})
```


#### [2.2 Promise.prototype.catch](#)
catch只接受一个参数: onRejected处理程序。事实上,这个方法就是一个语法糖 
Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。

上面代码中，getJSON方法返回一个Promise对象，如果该对象状态变为Resolved，则会调用then方法指定的回调函数；
如果异步操作抛出错误，状态就会变为Rejected，就会调用catch方法指定的回调函数，处理这个错误。另外，then方法
指定的回调函数，如果运行中抛出错误，也会被catch方法捕获。

```javascript
let promise = new Promise(function(resolve, reject) {
    resolve('ok');
    throw new Error('test');
}).then(function(value) { console.log(value) })
    .catch(function(error) { console.log(error.message) });
```


#### [2.3 Promise.prototype.finally](#)
finally:该方法用来制定不管Promise对象最后状态如何，都会执行的操作 该方法是 **ES2018** 引入标准的。

finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的promise状态到底是fulfilled（成功）还是rejected（失败），这表明，finally方法里面的操作，应该
是与状态无关的，不依赖与promise的执行结果。

```javascript
promise
.then(result => {/* ··· */})
.catch(error => {/* ··· */})
.finally(() => {/* ··· */});

//例子
server.listen(port)
  .then(function () {
    // ...
  })
  .finally(server.stop);
```

### [3. 期约连锁与期约合成](#)
多个期约组合在一起可以构成强大的代码逻辑。这种组合可以通过两种方式实现：期约连锁与期约
合成。前者就是一个期约接一个期约地拼接，后者则是将多个期约组合为一个期约。

#### [3.1 Promise.all()](#)
Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。 方法接受一个数组作为参数 如果参数不是 Promise类型将会转换为 Promise类型。
* Promise.all方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。
* 如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。

```javascript
const p = Promise.all([p1, p2, p3]);
//p的状态由p1、p2、p3决定，分成两种情况。
/*
（1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的
返回值组成一个数组，传递给p的回调函数。

（2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的
实例的返回值，会传递给p的回调函数。
*/
```

```javascript
// 生成一个Promise对象的数组
const promises = [2, 3, 5, 7, 11, 13].map(function (id) {
  return getJSON('/post/' + id + ".json");
});

Promise.all(promises).then(function (posts) {
  // ...
}).catch(function(reason){
  // ...
});
```
#### [3.1 要成功就全成功](#)
```javascript
let p1 = new Promise((resolve,reject)=>{
    resolve("p1 执行成功");
});

let p2 = new Promise((resolve,reject)=>{
    resolve("p2 执行成功");
});

let p3 = new Promise((resolve,reject)=>{
    resolve("p3 执行成功");
});

let p = Promise.all([p1,p2,p3]).then( result=>{
    console.log(result);
    //[ 'p1 执行成功', 'p2 执行成功', 'p3 执行成功' ]
}).catch(error =>{
    console.log(error);
})
```
#### [3.2 一个失败全失败](#)

```javascript
 p1 = new Promise((resolve,reject)=>{
    let x = 1;
    let x = 1;
    resolve("p1 执行成功");
});

let p2 = new Promise((resolve,reject)=>{
    resolve("p2 执行成功");
});

let p3 = new Promise((resolve,reject)=>{
    resolve("p3 执行成功");
});

let p = Promise.all([p1,p2,p3]).then( result=>{
    console.log(result);
}).catch(error =>{
    console.log("error:");
    console.log(error);
    /*
    error:
    _index.html:28 SyntaxError: Identifier 'x' has already been declared
        at new Promise (<anonymous>)
        at index.html:9

    */
});
```
#### [3.3 Promise.race()](#)
Promise.race方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
* 跑多个任务，只要一个完成就行。

```javascript
const p = Promise.race([p1, p2, p3]);
/*
上面代码中，只要p1、p2、p3之中有一个实例率先改变状态，p的状态就
跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。
*/
```

#### [3.4 Promise.try()](#)
database.users.get()可能还会抛出同步错误（比如数据库连接错误，具体要看实现方法），这时你就不得不用try...catch去捕获。

简而言之，Promise.try就像promiseObject.then，但是不需要前面的 promise 对象。现在这仍然有点模糊，所以让我们从一个例子开始。

对于那些未支持Promise.try的 Promise 实现形式，只要它们的 Promise 构造函数可以捕获同步错误，就可以很容易地实现Promise.try功能
。ES6 Promise的构造函数就能够捕获同步错误，所以我们可以这样实现Promise.try：


```javascript
'use strict';
export function promiseTry(func) {
    return new Promise(function(resolve, reject) {
        resolve(func());
    });
}
```
如果如此使用try，会有些麻烦
```javascript
try {
  database.users.get({id: userId})
  .then(...)
  .catch(...)
} catch (e) {
  // ...
}
```
上面这样的写法就很笨拙了，这时就可以统一用promise.catch()捕获所有同步和异步的错误。
```javascript
Promise.try(database.users.get({id: userId}))
  .then(...)
  .catch(...)
```

#### [3.5 非重入期约方法](#)
当期约进入落定状态时，与该状态相关的处理程序仅仅会被 **排期**，而非立即执行。跟在添加这个处
理程序的代码之后的同步代码一定会在处理程序之前先执行。

```javascript
// 创建解决的期约
let p = Promise.resolve();
// 添加解决处理程序
// 直觉上，这个处理程序会等期约一解决就执行
p.then(() => console.log('onResolved handler'));
// 同步输出，证明 then()已经返回
console.log('then() returns');
// 实际的输出：
// then() returns
// onResolved handler 
```
决期约上调用 then()会把 onResolved 处理程序推进消息队列。
在一个解决期约上调用 then()会把 onResolved 处理程序推进消息队列。但这个
处理程序在当前线程上的同步代码执行完成前不会执行。因此，跟在 then()后面的同步代码一定先于
处理程序执行。

```javascript
let p1 = Promise.resolve('foo');
p1.then((value) => console.log(value)); // foo

let p2 = Promise.reject('bar');
p2.catch((reason) => console.log(reason)); // bar 
```
到了落定状态后，期约会提供其解决值（如果兑现）或其拒绝理由（如果拒绝）给相关状态的处理
程序。拿到返回值后，就可以进一步对这个值进行操作。

#### [3.6 拒绝期约与拒绝错误处理](#)
拒绝期约类似于 throw()表达式，因为它们都代表一种程序状态，即需要中断或者特殊处理。在期
约的执行函数或处理程序中抛出错误会导致拒绝，对应的错误对象会成为拒绝的理由。因此以下这些期
约都会以一个错误对象为由被拒绝：

```javascript
let p1 = new Promise((resolve, reject) => reject(Error('foo')));
let p2 = new Promise((resolve, reject) => { throw Error('foo'); });
let p3 = Promise.resolve().then(() => { throw Error('foo'); });
let p4 = Promise.reject(Error('foo'));

setTimeout(console.log, 0, p1); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p2); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p3); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p4); // Promise <rejected>: Error: foo
// 也会抛出 4 个未捕获错误
```

#### [3.7 期约图](#)
一个期约可以有任意多个处理程序，可以构建有向非循环图的结构。

每个期约都是图中的一个节点，使用实例方法添加的处理程序是有向节点。图的方向就是期约的解决或拒绝顺序。
```javascript
//     A
//    /  \
//   B    C
//  / \  / \
// D  E  F   G
let A = new Promise((resolve, reject) => {
  console.log('A');
  resolve();
 });
 let B = A.then(() => console.log('B'));
 let C = A.then(() => console.log('C'));
 B.then(() => console.log('D'));
 B.then(() => console.log('E'));
 C.then(() => console.log('F'));
 C.then(() => console.log('G')); 

```

### [4. 期约扩展](#)
ES6 期约实现是很可靠的，但它也有不足之处。比如，很多第三方期约库实现中具备而 ECMAScript
规范却未涉及的两个特性：**期约取消**和**进度追踪**。

#### [4.1 期约取消](#)
我们经常会遇到期约正在处理过程中，程序却不再需要其结果的情形。这时候如果能够取消期约就好了。

> 实际上，TC39 委员会也曾准备增加这个特性，但相关提案最终被撤回了。
> 结果，ES6 期约被认为是“激进的”：只要期约的逻辑开始执行，就没有办法阻止它执行到完成。

实际上，可以在现有实现基础上提供一种临时性的封装，以实现取消期约的功能。

```javascript
class CancelToken {
	constructor(cancelFn) {
    this.promise = new Promise((resolve, reject)=> {
      cancelFn(resolve)
    })
  }
}
function cancelableDelayResolve() {
  
}
const id = setTimeout(()=> {
  resolve()
}, delay)
const cancelToken = new CancelToken((cancelCb)=> {
	xxxx.addEventListener('click', cancelCb)
}) 
cancelToken.promise.then(()=>clearTimeout(id))
```

#### [4.2 期约进度通知](#)
通过扩展监控期约执行进度。

扩展Promise类，为它添加notify()方法

```javascript
class TrackablePromise extends Promise {
  constructor(executor) {
    const notifyHandlers = []
    
    super((resolve, reject)=> {
      return executor(resolve, reject, (status) => {
        notifyHandlers.map((handler) => handler(status))
      })
    })
    this.notifyHandlers = notifyHandlers
  }
  
  notify(notifyHandler) {
    this.notifyHandlers.push(notifyHandler)
    return this
  }
}

// 这样就可以执行函数时使用notify了。
let p = new TrackablePromise((resolve, reject, notify)=> {
  function countdown(x) {
    if(x > 0) {
      notify(`${20 * x}% remaining`)
      setTimeout(() => countdown(x - 1), 1000)
    }else {
      resolve()
    }
  }
  countdown(5)
})

p.notify((x)=> setTimeout(console.log, 0, 'progress:', x))
p.then(()=> setTimeout(console.log, 0 , 'completed'))
// （约 1 秒后）80% remaining
// （约 2 秒后）60% remaining
// （约 3 秒后）40% remaining
// （约 4 秒后）20% remaining
// （约 5 秒后）completed 
```

### [5. async和await](#)
async和await是建立在Promise之上的高级抽象，使得异步代码的编写和阅读更加接近于同步代码的风格。

#### [5.1 Async 函数](#)
通过在函数声明前加上async关键字，可以将任何函数转换为返回Promise的异步函数。这意味着你可以使用 `.then()`和`.catch()`来处理它们的结果。

代码示例：创建一个async函数
```javascript
async function asyncFunction() {
    return "异步操作完成";
}

asyncFunction().then(value => console.log(value)); // 输出：异步操作完成
```

**await** 关键字

await关键字只能在async函数内部使用。它可以暂停async函数的执行，等待Promise的解决（resolve），然后以Promise的值继续执行函数。

在async函数中使用await
```javascript
async function asyncFunction() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("完成"), 1000)
  });

  let result = await promise; // 等待，直到promise解决 (resolve)
  console.log(result); // "完成"
}

asyncFunction();
```
await 表示强制等待的意思，await 关键字的后面要跟一个Promise 对象，他总是等到该Promise 对象 resolve 成功之后执行，并且会返回resolve 的结果
```javascript
async function test () {
    // await 总是会等到后面的 Promise 执行完 resolve
    // async  /  await 就是让我们用同步的方法去写异步
    const result = await new Promise(function (resolve , reject){
        setTimeout(function(){
            resolve(5)
        },5000)
        alert(result)
    })
}
```

#### [5.2 错误处理](#)
在 `async/await` 中，错误处理可以通过传统的 `try...catch` 语句实现，这使得异步代码的错误处理更加直观。

代码示例：使用 `try...catch` 处理错误。
```javascript
async function asyncFunction() {
  try {
    let response = await fetch('http://example.com');
    let data = await response.json();
    // 处理数据
  } catch (error) {
    console.log('捕获到错误：', error);
  }
}

asyncFunction();
```
在实际应用中，async和await使得处理复杂的异步逻辑更加简单，尤其是在涉及多个依次执行的异步操作时。

前几年的版本时，浏览器执行过程中await 会阻塞后续代码，将后续的代码放入微任务队列中，但是现在的浏览器执行代码时会给紧跟在await关键字后的代码开小灶，相当于紧随在await关键字后的代码变成同步代码，但是再往后的代码依旧会被推入微任务队列。


### [6. 手写Promise](#)
为了兼容以往对异步处理的方法，以及解决以往异步处理事件和回调的缺陷，ES6使用了Promise A+规范，来专门处理异步问题：避免回调地狱，使异步代码更加整洁、统一。

**promise A+规范**：

在promiseA+中，把每一个异步任务都看做一个promise对象，每一个任务对象都有两个阶段（`unsettled`，`settled`）,三个状态（`pending`，`resolved`，`rejected`）。

**两个阶段**：

* `unsettled`：事情未解决阶段，事情还没有结果。
* `settled`：事情已解决阶段，无论是成功，还是失败，已经有结果了。

**三个状态：**
* `padding`：挂起，处于未解决阶段。事情还没有结果输出，promise对象为挂起状态。
* `resolved`：已处理，处于已解决阶段。已经有了成功的结果，可以按照正常逻辑进行下去，并可以传递一个成功信息，后续可以用.then的onFulfiled处理。
* `rejected`：已拒绝，处于已解决阶段，已经有了失败的结果，无法按照正常逻辑进行下去，可以传递一个错误信息，后续可以用.then的onRejected处理，或使用catch处理。

两个阶段是由unsettle -> settled，不可逆。

三个状态是由padding -> resolved/rejected，不可逆，且resolved和rejected之间的状态不可以互相切换。
也就是说，promise对象一旦有了结果，结果不可改变，不可消失。

<img src="./static/e496723269a84b4f95ad58da531b7126~tplv-k3u1fbpfcp-zoom-in-crop-mark_1512_0_0_0.png" width="700px" />

promise的基本使用
```javascript
const p1 = new Promise((resolve, reject) => {
  //此部分为同步部分
  //此部分决定Promise的状态，未决定之前为Padding不能进行后续对该Promise的处理
  //resolve和reject只能接受和传递一个参数
  //resolve将Promise对象推入已处理状态
  //reject将Promise对象推入已拒绝状态
  resolve("请求成功");
  //状态一旦改变就不可以更改
  //reject('请求失败')
});
​
//处理Promise的结果，为异步部分。
//若对应的promise为pending，则会加入作业队列，等待Promise结果。
//若Promise结果为resolved或rejected，加入微任务队列等待执行JS引擎轮询到立马执行。
p1.then(
  (value) => {
    //此部分为onFulfilled，也就是thenabled处理，Promise状态为resolved接收参数并执行此部分代码。
    console.log(`Promise已处理，接收到传值：${value}`);
  },
  (err) => {
    //此部分为onRejected，也就是catchabled处理，Promise状态为reject接收参数并执行此部分代码。
    //Promise对象的then方法调用中也可以不写此部分，不进行错误处理，在Promise对象的catch方法中进行错误处理。
    console.log(`Promise已拒绝,接收到原因：${err}`);
  }
);
​
//Promise并没有消除回调，只是让回调变得可控了。
```


```javascript
//起步构建
// 1.用类创建Promise，类中需要有个执行器executor
// 2.执行者中发生错误，交给异常状态处理
// 3.执行者中状态只能触发一次，状态触发一次之后，不能修改状态
// 4.执行者中的this，由调用执行者的作用域决定，因此我们需要将执行者中的this绑定为我们创建的Promise对象。
// 5.在构造函数中需要为Promise对象创建status和value记录Promise的状态和传值。
​
class MyPromise {
    static PENDING = 'pending'
    static FULFILLED = 'fulfilled'
    static REJECTED = 'rejected'
​
    constructor(executor) {
        this.status = MyPromise.PENDING;
        this.value = null;
        this.callbacks = [];
        try {
            executor(this.resolve.bind(this), this.reject.bind(this))
        } catch (error) {
            this.reject(error)
        }
    }
​
    resolve(value) {
        if (this.status == MyPromise.PENDING) {
            this.status = MyPromise.FULFILLED;
            this.value = value
            setTimeout(() => {
                this.callbacks.map(item => {
                    item.onFulfilled(this.value);
                })
            })
​
        }
    }
​
    reject(reason) {
        if (this.status == MyPromise.PENDING) {
            this.status = MyPromise.REJECTED;
            this.value = reason
            setTimeout(() => {
                this.callbacks.map(item => {
                    item.onRejected(this.value);
                })
            })
​
        }
    }
​
    //开始写then方法
    //1.then接收2个参数，一个成功回调函数，一个失败回调函数
    //2.then中发生错误，状态为rejected，交给下一个then处理
    //3.then返回的也是一个Promise
    //4.then的参数值可以为空，可以进行传值穿透
    //5.then中的方法是异步执行的
    //6.then需要等promise的状态改变后，才执行，并且异步执行
    //7.then是可以链式操作的
    //8.then的onFulfilled可以用来返回Promise对象，并且then的状态将以这个Promise为准
    //9.then的默认状态是成功的，上一个Promise对象的状态不会影响下一个then的状态
    //10.then返回的promise对象不是then相同的promise
    then(onFulfilled, onRejected) {
        if (typeof onFulfilled != 'function') {
            onFulfilled = value => value
        }
​
        if (typeof onRejected != 'function') {
            onRejected = reason => reason
        }
​
        let promise = new MyPromise((resolve, reject) => {
            if (this.status == MyPromise.FULFILLED) {
                setTimeout(() => {
                    this.parse(promise, onFulfilled(this.value), resolve, reject)
                });
​
            }
​
            if (this.status == MyPromise.REJECTED) {
                setTimeout(() => {
                    this.parse(promise, onRejected(this.value), resolve, reject)
                })
​
            }
​
            if (this.status == MyPromise.PENDING) {
                this.callbacks.push({
                    onFulfilled: value => {
                        this.parse(promise, onFulfilled(value), resolve, reject)
                    },
                    onRejected: reason => {
                        this.parse(promise, onRejected(reason), resolve, reject)
                    }
                });
​
            }
        })
        return promise
    }
​
    //整理冗余代码
    parse(promise, result, resolve, reject) {
        if (promise == result) {
            throw new TypeError('Chaining cycle detected for promise')
        }
        try {
            if (result instanceof MyPromise) {
                result.then(resolve, reject)
            } else {
                resolve(result)
            }
        } catch (error) {
            reject(error)
        }
    }
​
    //Promise的静态方法，resolve
    static resolve(value) {
        return new MyPromise((resolve, reject) => {
            if (value instanceof MyPromise) {
                value.then(resolve, reject)
            } else {
                resolve(value)
            }
        })
    }
​
    //Promise的静态方法，reject
    static reject(reason) {
        return new MyPromise((resolve, reject) => {
            reject(reason)
        })
    }
​
    //Promise的静态方法，all
    static all(promises) {
        let values = [];
        return new MyPromise((resolve, reject) => {
            promises.forEach(promise => {
                if (promise.status == MyPromise.FULFILLED) {
                    values.push(promise.value)
                } else if (promise.status == MyPromise.REJECTED) {
                    reject(promise.value)
                }
                if (values.length == promises.length) {
                    resolve(values)
                }
            });
        })
    }
​
    //Promise的静态方法，race
    static race(promises) {
        return new MyPromise((resolve, reject) => {
            promises.forEach(promise => {
                promise.then(value => {
                    resolve(value)
                })
            });
        })
    }
​
    //Promise的静态方法，race
    catch (onRejected) {
        return this.then(null, onRejected)
    }
}
```


**参考引用**
* [浅谈JavaScript中的Promise、Async和Await](https://juejin.cn/post/7320288262400311333?searchId=2024112022005837C301FF756361A8742E)

-----
时间: 2022/2/3 12:22
